# Generated by Django 6.0.8 on 2026-08-20 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClickToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=16, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('site', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('landing_url', models.TextField(blank=True, null=True)),
                ('referrer', models.TextField(blank=True, null=True)),
                ('listing_id', models.CharField(blank=True, max_length=128, null=True)),
                ('gclid', models.CharField(blank=True, max_length=512, null=True)),
                ('gbraid', models.CharField(blank=True, max_length=512, null=True)),
                ('wbraid', models.CharField(blank=True, max_length=512, null=True)),
                ('yclid', models.CharField(blank=True, max_length=512, null=True)),
                ('fbclid', models.CharField(blank=True, max_length=512, null=True)),
                ('fbp', models.CharField(blank=True, max_length=512, null=True)),
                ('fbc', models.CharField(blank=True, max_length=512, null=True)),
                ('utm_source', models.CharField(blank=True, max_length=512, null=True)),
                ('utm_medium', models.CharField(blank=True, max_length=512, null=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=512, null=True)),
                ('utm_content', models.CharField(blank=True, max_length=512, null=True)),
                ('utm_term', models.CharField(blank=True, max_length=512, null=True)),
                ('ga_client_id', models.CharField(blank=True, max_length=128, null=True)),
                ('ym_client_id', models.CharField(blank=True, max_length=128, null=True)),
                ('is_test', models.BooleanField(default=False)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('schema_version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MessageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=32)),
                ('chat_ref', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('ts', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('direction', models.CharField(choices=[('in', 'in'), ('out', 'out')], max_length=8)),
                ('author_type', models.CharField(choices=[('customer', 'customer'), ('bot', 'bot'), ('human_agent', 'human_agent'), ('unknown', 'unknown')], max_length=16)),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('reply_to_id', models.CharField(blank=True, max_length=255, null=True)),
                ('text_len', models.PositiveIntegerField(default=0)),
                ('text_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('referral', models.JSONField(blank=True, null=True)),
                ('raw_meta', models.JSONField(blank=True, null=True)),
                ('deal_id', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['phone', 'direction', 'ts'], name='attribution_phone_ab6790_idx')],
            },
        ),
        migrations.CreateModel(
            name='StatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(max_length=32)),
                ('ts', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('recipient_id', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('conversation_id', models.CharField(blank=True, max_length=128, null=True)),
                ('conversation_origin_type', models.CharField(blank=True, max_length=64, null=True)),
                ('conversation_expiration_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.JSONField(blank=True, null=True)),
                ('pricing', models.JSONField(blank=True, null=True)),
                ('errors', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('message_id', 'status'), name='attribution_status_unique')],
            },
        ),
        migrations.CreateModel(
            name='DealAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_id', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('phone', models.CharField(db_index=True, max_length=32)),
                ('chat_ref', models.CharField(blank=True, max_length=64, null=True)),
                ('first_inbound_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('attribution_source', models.CharField(choices=[('meta_referral', 'meta_referral'), ('site_code', 'site_code'), ('none', 'none')], max_length=32)),
                ('attribution_status', models.CharField(choices=[('matched', 'matched'), ('code_missing', 'code_missing'), ('code_not_found', 'code_not_found')], max_length=32)),
                ('referral', models.JSONField(blank=True, null=True)),
                ('pushed_to_bitrix_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_attributions', to='attribution.clicktoken')),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('deal_id__isnull', False)), fields=('deal_id',), name='attribution_deal_unique')],
            },
        ),
    ]
